// const { MaxBinaryHeap } = require('./MaxBinaryHeap')

// const maxHeap = new MaxBinaryHeap()

// maxHeap.insert(11)
// maxHeap.insert(3)
// maxHeap.insert(20)
// maxHeap.insert(18)
// maxHeap.insert(128)
// maxHeap.insert(183)
// maxHeap.insert(8)
// maxHeap.print()
// maxHeap.extractMax()
// maxHeap.extractMax()
// maxHeap.print()
// maxHeap.extractMax()
// maxHeap.extractMax()
// maxHeap.extractMax()
// maxHeap.extractMax()
// maxHeap.extractMax()
// maxHeap.print()
